### ISSUE TITLE
There is no Comment after Backup

### ISSUE THREAD

**Issue by mhoelli** [r23/MyOOS-Dumper#8]
Hello,
i think there is an misspell in line 49 of filemanagement.php.
'dk' ist not transmitted via $_POST.
By rewriting constant to 'dumpKommentar' it works.
$dk = filter_string_polyfill(filter_input(INPUT_POST, 'dumpKommentar'));

**Comment by r23** [comment]
Thank you for the tip. I have adopted the changes after checking.

https://github.com/r23/MyOOS-Dumper/commit/000db384bd5a6aae5a7625dca350409ad28c8069
