### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function diskfreespace() 

### ISSUE THREAD

**Issue by speedloc** [r23/MyOOS-Dumper#9]
hi in myoos dumper i have problem and get error: 
Fatal error: Uncaught Error: Call to undefined function diskfreespace() in /inc/functions_global.php:190
it is since upgrade from myswldumper to myoos dumper. 
php 8.2.7 was using in debian

**Comment by r23** [comment]
Thanks for the tip. 

The correct name of the function is **disk_free_space** [](https://www.php.net/manual/en/function.disk-free-space.php)

 I have just changed it [](https://github.com/r23/MyOOS-Dumper/commit/3c75b5d7ebbb8dde0fe40f58358d0561d02923a4)
